#!/bin/bash
python3 -- <<END
# simple gui for xscreenfilter by caph1993
import gi
import subprocess

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

class MySliderApplet(Gtk.Box):
    def __init__(self):
        Gtk.Box.__init__(self, orientation=Gtk.Orientation.VERTICAL, spacing=6)
        
        default_value1 = 3000
        default_value2 = 0.5

        try:
            with open('/tmp/gxscreenfilter_values', 'r') as f:
                values = f.read().split()
                if len(values) == 2:
                    default_value1 = int(values[0])
                    default_value2 = float(values[1])
        except FileNotFoundError:
            pass
        
        adjustment1 = Gtk.Adjustment(value=default_value1, lower=0, upper=6500, step_increment=100, page_increment=100, page_size=0)
        self.slider1 = Gtk.Scale(orientation=Gtk.Orientation.HORIZONTAL, adjustment=adjustment1)
        self.slider1.set_digits(0)
        self.slider1.set_hexpand(True)
        self.slider1.set_valign(Gtk.Align.CENTER)
        self.slider1.connect("value-changed", self.on_slider_changed)
        
        adjustment2 = Gtk.Adjustment(value=default_value2, lower=0, upper=1, step_increment=0.01, page_increment=0.1, page_size=0)
        self.slider2 = Gtk.Scale(orientation=Gtk.Orientation.HORIZONTAL, adjustment=adjustment2)
        self.slider2.set_digits(2)
        self.slider2.set_hexpand(True)
        self.slider2.set_valign(Gtk.Align.CENTER)
        self.slider2.connect("value-changed", self.on_slider_changed)
        
        self.pack_start(self.slider1, True, True, 0)
        self.pack_start(self.slider2, True, True, 0)
        
    def on_slider_changed(self, widget):
        value1 = int(self.slider1.get_value())
        value2 = round(self.slider2.get_value(), 2)
        
        with open('/tmp/gxscreenfilter_values', 'w') as f:
            f.write(f"{value1} {value2}")
        
        subprocess.run(["xscreenfilter", str(value1), str(value2)])

def main():
    Gtk.init(None)
    window = Gtk.Window(title="gxscreenfilter")
    window.set_default_size(400, 100)
    window.connect("destroy", Gtk.main_quit)
    
    applet = MySliderApplet()
    window.add(applet)
    
    window.show_all()
    Gtk.main()

if __name__ == "__main__":
    main()
END